#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Moyeu.Resource", IsApplication=true)]

namespace Moyeu
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::XamSvg.Resource.String.library_name = global::Moyeu.Resource.String.library_name;
		}
		
		public partial class Animator
		{
			
			// aapt resource value: 0x7f040000
			public const int frag_slide_in = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int frag_slide_out = 2130968577;
			
			static Animator()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animator()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int adSize = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int adUnitId = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int cameraBearing = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int cameraTargetLat = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cameraTargetLng = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int cameraTilt = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int cameraZoom = 2130771975;
			
			// aapt resource value: 0x7f010002
			public const int mapType = 2130771970;
			
			// aapt resource value: 0x7f010008
			public const int uiCompass = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int uiRotateGestures = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int uiScrollGestures = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int uiTiltGestures = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int uiZoomControls = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int uiZoomGestures = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int useViewLifecycle = 2130771982;
			
			// aapt resource value: 0x7f01000f
			public const int zOrderOnTop = 2130771983;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070009
			public const int common_action_bar_splitter = 2131165193;
			
			// aapt resource value: 0x7f070000
			public const int common_signin_btn_dark_text_default = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int common_signin_btn_dark_text_disabled = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int common_signin_btn_dark_text_focused = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int common_signin_btn_dark_text_pressed = 2131165185;
			
			// aapt resource value: 0x7f070008
			public const int common_signin_btn_default_background = 2131165192;
			
			// aapt resource value: 0x7f070004
			public const int common_signin_btn_light_text_default = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int common_signin_btn_light_text_disabled = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int common_signin_btn_light_text_focused = 2131165191;
			
			// aapt resource value: 0x7f070005
			public const int common_signin_btn_light_text_pressed = 2131165189;
			
			// aapt resource value: 0x7f07000b
			public const int common_signin_btn_text_dark = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int common_signin_btn_text_light = 2131165196;
			
			// aapt resource value: 0x7f07000a
			public const int pane_btn_bg_selected = 2131165194;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int common_signin_btn_icon_dark = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int common_signin_btn_icon_disabled_dark = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_signin_btn_icon_disabled_focus_dark = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_signin_btn_icon_disabled_focus_light = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_signin_btn_icon_disabled_light = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_signin_btn_icon_focus_dark = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_signin_btn_icon_focus_light = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_signin_btn_icon_light = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_signin_btn_icon_normal_dark = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_signin_btn_icon_normal_light = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_signin_btn_icon_pressed_dark = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_signin_btn_icon_pressed_light = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_signin_btn_text_dark = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_signin_btn_text_disabled_dark = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_signin_btn_text_disabled_focus_dark = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_signin_btn_text_disabled_focus_light = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_signin_btn_text_disabled_light = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_signin_btn_text_focus_dark = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_signin_btn_text_focus_light = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_signin_btn_text_light = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_signin_btn_text_normal_dark = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_signin_btn_text_normal_light = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_signin_btn_text_pressed_dark = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_signin_btn_text_pressed_light = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int drawer_shadow = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int fire = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int flash_bar_background = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int ic_action_mylocation = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int ic_action_refresh = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int ic_action_search = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int ic_drawer = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int ic_drawer_map = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int ic_drawer_rentals = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int ic_drawer_star = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int ic_plusone_medium_off_client = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int ic_plusone_small_off_client = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int ic_plusone_standard_off_client = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int ic_plusone_tall_off_client = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int Icon = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int info_pane_btn_bg = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int info_pane_header_bg = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int info_pane_underline = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int pane_item_bg = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int pane_item_bg_normal = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int pane_item_bg_selected = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int pattern = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int station_lock = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int texture_pattern = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int time_cell_bg = 2130837553;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080016
			public const int BikeNumber = 2131230742;
			
			// aapt resource value: 0x7f080040
			public const int FlashBarLayout = 2131230784;
			
			// aapt resource value: 0x7f080041
			public const int FlashBarProgress = 2131230785;
			
			// aapt resource value: 0x7f080042
			public const int FlashBarText = 2131230786;
			
			// aapt resource value: 0x7f080020
			public const int InfoViewBikeNumber = 2131230752;
			
			// aapt resource value: 0x7f08001d
			public const int InfoViewName = 2131230749;
			
			// aapt resource value: 0x7f08001e
			public const int InfoViewSecondName = 2131230750;
			
			// aapt resource value: 0x7f080021
			public const int InfoViewSlotNumber = 2131230753;
			
			// aapt resource value: 0x7f080014
			public const int MainStationName = 2131230740;
			
			// aapt resource value: 0x7f08001b
			public const int PaneHeaderView = 2131230747;
			
			// aapt resource value: 0x7f080015
			public const int SecondStationName = 2131230741;
			
			// aapt resource value: 0x7f080018
			public const int SlotNumber = 2131230744;
			
			// aapt resource value: 0x7f08001c
			public const int StarButton = 2131230748;
			
			// aapt resource value: 0x7f080013
			public const int StationMap = 2131230739;
			
			// aapt resource value: 0x7f080043
			public const int UpdateTimeText = 2131230787;
			
			// aapt resource value: 0x7f08000a
			public const int aroundBikes = 2131230730;
			
			// aapt resource value: 0x7f08000d
			public const int aroundRacks = 2131230733;
			
			// aapt resource value: 0x7f08000e
			public const int aroundStar = 2131230734;
			
			// aapt resource value: 0x7f080007
			public const int aroundStation1 = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int aroundStation2 = 2131230728;
			
			// aapt resource value: 0x7f080019
			public const int bikeImageView = 2131230745;
			
			// aapt resource value: 0x7f08002c
			public const int bikeNumberImg = 2131230764;
			
			// aapt resource value: 0x7f080026
			public const int clockImg = 2131230758;
			
			// aapt resource value: 0x7f08003c
			public const int content_frame = 2131230780;
			
			// aapt resource value: 0x7f08003b
			public const int drawer_layout = 2131230779;
			
			// aapt resource value: 0x7f080032
			public const int gmapsBtn = 2131230770;
			
			// aapt resource value: 0x7f080027
			public const int historyTime1 = 2131230759;
			
			// aapt resource value: 0x7f080028
			public const int historyTime2 = 2131230760;
			
			// aapt resource value: 0x7f080029
			public const int historyTime3 = 2131230761;
			
			// aapt resource value: 0x7f08002a
			public const int historyTime4 = 2131230762;
			
			// aapt resource value: 0x7f08002b
			public const int historyTime5 = 2131230763;
			
			// aapt resource value: 0x7f08002d
			public const int historyValue1 = 2131230765;
			
			// aapt resource value: 0x7f08002e
			public const int historyValue2 = 2131230766;
			
			// aapt resource value: 0x7f08002f
			public const int historyValue3 = 2131230767;
			
			// aapt resource value: 0x7f080030
			public const int historyValue4 = 2131230768;
			
			// aapt resource value: 0x7f080031
			public const int historyValue5 = 2131230769;
			
			// aapt resource value: 0x7f080004
			public const int hybrid = 2131230724;
			
			// aapt resource value: 0x7f080011
			public const int icon = 2131230737;
			
			// aapt resource value: 0x7f08001a
			public const int infoPane = 2131230746;
			
			// aapt resource value: 0x7f08003d
			public const int left_drawer = 2131230781;
			
			// aapt resource value: 0x7f08003e
			public const int left_drawer_around = 2131230782;
			
			// aapt resource value: 0x7f080005
			public const int linearLayout1 = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int linearLayout2 = 2131230726;
			
			// aapt resource value: 0x7f080009
			public const int linearLayout3 = 2131230729;
			
			// aapt resource value: 0x7f08000c
			public const int linearLayout4 = 2131230732;
			
			// aapt resource value: 0x7f080025
			public const int linearLayout5 = 2131230757;
			
			// aapt resource value: 0x7f080022
			public const int lockImageView = 2131230754;
			
			// aapt resource value: 0x7f08003a
			public const int loginBtn = 2131230778;
			
			// aapt resource value: 0x7f080038
			public const int loginStatusProgress = 2131230776;
			
			// aapt resource value: 0x7f080039
			public const int loginStatusText = 2131230777;
			
			// aapt resource value: 0x7f08003f
			public const int map = 2131230783;
			
			// aapt resource value: 0x7f080057
			public const int menu_mylocation = 2131230807;
			
			// aapt resource value: 0x7f080059
			public const int menu_refresh = 2131230809;
			
			// aapt resource value: 0x7f080058
			public const int menu_search = 2131230808;
			
			// aapt resource value: 0x7f080000
			public const int none = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int normal = 2131230721;
			
			// aapt resource value: 0x7f080037
			public const int password = 2131230775;
			
			// aapt resource value: 0x7f080047
			public const int rentalFromStation = 2131230791;
			
			// aapt resource value: 0x7f08004a
			public const int rentalPrice = 2131230794;
			
			// aapt resource value: 0x7f080044
			public const int rentalTime = 2131230788;
			
			// aapt resource value: 0x7f080045
			public const int rentalTimePrimary = 2131230789;
			
			// aapt resource value: 0x7f080046
			public const int rentalTimeSecondary = 2131230790;
			
			// aapt resource value: 0x7f080048
			public const int rentalToStation = 2131230792;
			
			// aapt resource value: 0x7f080002
			public const int satellite = 2131230722;
			
			// aapt resource value: 0x7f08004d
			public const int space1 = 2131230797;
			
			// aapt resource value: 0x7f08004f
			public const int space2 = 2131230799;
			
			// aapt resource value: 0x7f080051
			public const int space3 = 2131230801;
			
			// aapt resource value: 0x7f080053
			public const int space4 = 2131230803;
			
			// aapt resource value: 0x7f08004b
			public const int space5 = 2131230795;
			
			// aapt resource value: 0x7f080055
			public const int space6 = 2131230805;
			
			// aapt resource value: 0x7f080056
			public const int space7 = 2131230806;
			
			// aapt resource value: 0x7f080023
			public const int stationLock = 2131230755;
			
			// aapt resource value: 0x7f08001f
			public const int stationStats = 2131230751;
			
			// aapt resource value: 0x7f080034
			public const int streetViewImg = 2131230772;
			
			// aapt resource value: 0x7f080033
			public const int streetViewSpinner = 2131230771;
			
			// aapt resource value: 0x7f080003
			public const int terrain = 2131230723;
			
			// aapt resource value: 0x7f080012
			public const int text = 2131230738;
			
			// aapt resource value: 0x7f080024
			public const int textView1 = 2131230756;
			
			// aapt resource value: 0x7f080050
			public const int textView10 = 2131230800;
			
			// aapt resource value: 0x7f080052
			public const int textView11 = 2131230802;
			
			// aapt resource value: 0x7f080054
			public const int textView12 = 2131230804;
			
			// aapt resource value: 0x7f080017
			public const int textView2 = 2131230743;
			
			// aapt resource value: 0x7f08000b
			public const int textView4 = 2131230731;
			
			// aapt resource value: 0x7f080049
			public const int textView5 = 2131230793;
			
			// aapt resource value: 0x7f080035
			public const int textView7 = 2131230773;
			
			// aapt resource value: 0x7f08004c
			public const int textView8 = 2131230796;
			
			// aapt resource value: 0x7f08004e
			public const int textView9 = 2131230798;
			
			// aapt resource value: 0x7f08000f
			public const int titleText = 2131230735;
			
			// aapt resource value: 0x7f080036
			public const int username = 2131230774;
			
			// aapt resource value: 0x7f080010
			public const int view1 = 2131230736;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f0a0000
			public const int google_play_services_version = 2131361792;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int DrawerAroundItem = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int DrawerHeader = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int DrawerItemLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int FavoriteItem = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int InfoPaneLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int LoginDialogLayout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Main = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int MapLayout = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int RentalItem = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int TestLayout = 2130903049;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0c0000
			public const int map_menu = 2131492864;
			
			// aapt resource value: 0x7f0c0001
			public const int rentals_menu = 2131492865;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f060000
			public const int bike = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int bike_number = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int bike_separator = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int clock = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int ic_lock = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int map_placeholder = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int pin = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int pin_locked = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int star_depressed = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int star_off = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int star_on = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int station_lock = 2131099659;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f09001c
			public const int app_name = 2131296284;
			
			// aapt resource value: 0x7f090015
			public const int auth_client_needs_enabling_title = 2131296277;
			
			// aapt resource value: 0x7f090016
			public const int auth_client_needs_installation_title = 2131296278;
			
			// aapt resource value: 0x7f090017
			public const int auth_client_needs_update_title = 2131296279;
			
			// aapt resource value: 0x7f090018
			public const int auth_client_play_services_err_notification_msg = 2131296280;
			
			// aapt resource value: 0x7f090019
			public const int auth_client_requested_by_msg = 2131296281;
			
			// aapt resource value: 0x7f090014
			public const int auth_client_using_bad_version_title = 2131296276;
			
			// aapt resource value: 0x7f09001f
			public const int close_drawer = 2131296287;
			
			// aapt resource value: 0x7f090006
			public const int common_google_play_services_enable_button = 2131296262;
			
			// aapt resource value: 0x7f090005
			public const int common_google_play_services_enable_text = 2131296261;
			
			// aapt resource value: 0x7f090004
			public const int common_google_play_services_enable_title = 2131296260;
			
			// aapt resource value: 0x7f090003
			public const int common_google_play_services_install_button = 2131296259;
			
			// aapt resource value: 0x7f090001
			public const int common_google_play_services_install_text_phone = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int common_google_play_services_install_text_tablet = 2131296258;
			
			// aapt resource value: 0x7f090000
			public const int common_google_play_services_install_title = 2131296256;
			
			// aapt resource value: 0x7f09000c
			public const int common_google_play_services_invalid_account_text = 2131296268;
			
			// aapt resource value: 0x7f09000b
			public const int common_google_play_services_invalid_account_title = 2131296267;
			
			// aapt resource value: 0x7f09000a
			public const int common_google_play_services_network_error_text = 2131296266;
			
			// aapt resource value: 0x7f090009
			public const int common_google_play_services_network_error_title = 2131296265;
			
			// aapt resource value: 0x7f09000d
			public const int common_google_play_services_unknown_issue = 2131296269;
			
			// aapt resource value: 0x7f090010
			public const int common_google_play_services_unsupported_date_text = 2131296272;
			
			// aapt resource value: 0x7f09000f
			public const int common_google_play_services_unsupported_text = 2131296271;
			
			// aapt resource value: 0x7f09000e
			public const int common_google_play_services_unsupported_title = 2131296270;
			
			// aapt resource value: 0x7f090011
			public const int common_google_play_services_update_button = 2131296273;
			
			// aapt resource value: 0x7f090008
			public const int common_google_play_services_update_text = 2131296264;
			
			// aapt resource value: 0x7f090007
			public const int common_google_play_services_update_title = 2131296263;
			
			// aapt resource value: 0x7f090012
			public const int common_signin_button_text = 2131296274;
			
			// aapt resource value: 0x7f090013
			public const int common_signin_button_text_long = 2131296275;
			
			// aapt resource value: 0x7f09001b
			public const int hello = 2131296283;
			
			// aapt resource value: 0x7f09001a
			public const int library_name = 2131296282;
			
			// aapt resource value: 0x7f09001e
			public const int open_drawer = 2131296286;
			
			// aapt resource value: 0x7f09001d
			public const int search_hint = 2131296285;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f0b0000
			public const int drawer_item_shadow = 2131427328;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f050000
			public const int searchable = 2131034112;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] AdsAttrs = new int[]
			{
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int AdsAttrs_adSize = 0;
			
			// aapt resource value: 1
			public const int AdsAttrs_adUnitId = 1;
			
			public static int[] MapAttrs = new int[]
			{
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983};
			
			// aapt resource value: 1
			public const int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 2
			public const int MapAttrs_cameraTargetLat = 2;
			
			// aapt resource value: 3
			public const int MapAttrs_cameraTargetLng = 3;
			
			// aapt resource value: 4
			public const int MapAttrs_cameraTilt = 4;
			
			// aapt resource value: 5
			public const int MapAttrs_cameraZoom = 5;
			
			// aapt resource value: 0
			public const int MapAttrs_mapType = 0;
			
			// aapt resource value: 6
			public const int MapAttrs_uiCompass = 6;
			
			// aapt resource value: 7
			public const int MapAttrs_uiRotateGestures = 7;
			
			// aapt resource value: 8
			public const int MapAttrs_uiScrollGestures = 8;
			
			// aapt resource value: 9
			public const int MapAttrs_uiTiltGestures = 9;
			
			// aapt resource value: 10
			public const int MapAttrs_uiZoomControls = 10;
			
			// aapt resource value: 11
			public const int MapAttrs_uiZoomGestures = 11;
			
			// aapt resource value: 12
			public const int MapAttrs_useViewLifecycle = 12;
			
			// aapt resource value: 13
			public const int MapAttrs_zOrderOnTop = 13;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
