#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Moyeu.Resource", IsApplication=true)]

namespace Moyeu
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MobileHtmlAgilityPack.Resource.String.library_name = global::Moyeu.Resource.String.library_name;
			global::XamSvg.Resource.String.library_name = global::Moyeu.Resource.String.library_name;
		}
		
		public partial class Animator
		{
			
			// aapt resource value: 0x7f040000
			public const int frag_slide_in = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int frag_slide_out = 2130968577;
			
			static Animator()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animator()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public const int cameraBearing = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int cameraTargetLat = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int cameraTargetLng = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int cameraTilt = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cameraZoom = 2130771973;
			
			// aapt resource value: 0x7f010000
			public const int mapType = 2130771968;
			
			// aapt resource value: 0x7f010006
			public const int uiCompass = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int uiRotateGestures = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int uiScrollGestures = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int uiTiltGestures = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int uiZoomControls = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int uiZoomGestures = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int useViewLifecycle = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int zOrderOnTop = 2130771981;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f080009
			public const int common_action_bar_splitter = 2131230729;
			
			// aapt resource value: 0x7f080000
			public const int common_signin_btn_dark_text_default = 2131230720;
			
			// aapt resource value: 0x7f080002
			public const int common_signin_btn_dark_text_disabled = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int common_signin_btn_dark_text_focused = 2131230723;
			
			// aapt resource value: 0x7f080001
			public const int common_signin_btn_dark_text_pressed = 2131230721;
			
			// aapt resource value: 0x7f080008
			public const int common_signin_btn_default_background = 2131230728;
			
			// aapt resource value: 0x7f080004
			public const int common_signin_btn_light_text_default = 2131230724;
			
			// aapt resource value: 0x7f080006
			public const int common_signin_btn_light_text_disabled = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int common_signin_btn_light_text_focused = 2131230727;
			
			// aapt resource value: 0x7f080005
			public const int common_signin_btn_light_text_pressed = 2131230725;
			
			// aapt resource value: 0x7f08000b
			public const int common_signin_btn_text_dark = 2131230731;
			
			// aapt resource value: 0x7f08000c
			public const int common_signin_btn_text_light = 2131230732;
			
			// aapt resource value: 0x7f08000a
			public const int pane_btn_bg_selected = 2131230730;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int common_signin_btn_icon_dark = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int common_signin_btn_icon_disabled_dark = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_signin_btn_icon_disabled_focus_dark = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_signin_btn_icon_disabled_focus_light = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_signin_btn_icon_disabled_light = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_signin_btn_icon_focus_dark = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_signin_btn_icon_focus_light = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_signin_btn_icon_light = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_signin_btn_icon_normal_dark = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_signin_btn_icon_normal_light = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_signin_btn_icon_pressed_dark = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_signin_btn_icon_pressed_light = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_signin_btn_text_dark = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_signin_btn_text_disabled_dark = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_signin_btn_text_disabled_focus_dark = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_signin_btn_text_disabled_focus_light = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_signin_btn_text_disabled_light = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_signin_btn_text_focus_dark = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_signin_btn_text_focus_light = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_signin_btn_text_light = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_signin_btn_text_normal_dark = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_signin_btn_text_normal_light = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_signin_btn_text_pressed_dark = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_signin_btn_text_pressed_light = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int drawer_shadow = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int flash_bar_background = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int ic_action_mylocation = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int ic_action_refresh = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int ic_action_search = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int ic_drawer = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int ic_drawer_map = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int ic_drawer_rentals = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int ic_drawer_star = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int Icon = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int info_pane_btn_bg = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int info_pane_header_bg = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int pane_item_bg = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int pane_item_bg_normal = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int pane_item_bg_selected = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int pattern = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int texture_pattern = 2130837545;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090016
			public const int BikeNumber = 2131296278;
			
			// aapt resource value: 0x7f090030
			public const int FlashBarLayout = 2131296304;
			
			// aapt resource value: 0x7f090031
			public const int FlashBarProgress = 2131296305;
			
			// aapt resource value: 0x7f090032
			public const int FlashBarText = 2131296306;
			
			// aapt resource value: 0x7f09001f
			public const int InfoViewBikeNumber = 2131296287;
			
			// aapt resource value: 0x7f09001d
			public const int InfoViewName = 2131296285;
			
			// aapt resource value: 0x7f09001e
			public const int InfoViewSecondName = 2131296286;
			
			// aapt resource value: 0x7f090020
			public const int InfoViewSlotNumber = 2131296288;
			
			// aapt resource value: 0x7f090014
			public const int MainStationName = 2131296276;
			
			// aapt resource value: 0x7f09001b
			public const int PaneHeaderView = 2131296283;
			
			// aapt resource value: 0x7f090015
			public const int SecondStationName = 2131296277;
			
			// aapt resource value: 0x7f090018
			public const int SlotNumber = 2131296280;
			
			// aapt resource value: 0x7f09001c
			public const int StarButton = 2131296284;
			
			// aapt resource value: 0x7f090013
			public const int StationMap = 2131296275;
			
			// aapt resource value: 0x7f090033
			public const int UpdateTimeText = 2131296307;
			
			// aapt resource value: 0x7f09000a
			public const int aroundBikes = 2131296266;
			
			// aapt resource value: 0x7f09000d
			public const int aroundRacks = 2131296269;
			
			// aapt resource value: 0x7f09000e
			public const int aroundStar = 2131296270;
			
			// aapt resource value: 0x7f090007
			public const int aroundStation1 = 2131296263;
			
			// aapt resource value: 0x7f090008
			public const int aroundStation2 = 2131296264;
			
			// aapt resource value: 0x7f090019
			public const int bikeImageView = 2131296281;
			
			// aapt resource value: 0x7f09002c
			public const int content_frame = 2131296300;
			
			// aapt resource value: 0x7f09002b
			public const int drawer_layout = 2131296299;
			
			// aapt resource value: 0x7f090024
			public const int gmapsBtn = 2131296292;
			
			// aapt resource value: 0x7f090004
			public const int hybrid = 2131296260;
			
			// aapt resource value: 0x7f090011
			public const int icon = 2131296273;
			
			// aapt resource value: 0x7f09001a
			public const int infoPane = 2131296282;
			
			// aapt resource value: 0x7f09002d
			public const int left_drawer = 2131296301;
			
			// aapt resource value: 0x7f09002e
			public const int left_drawer_around = 2131296302;
			
			// aapt resource value: 0x7f090005
			public const int linearLayout1 = 2131296261;
			
			// aapt resource value: 0x7f090006
			public const int linearLayout2 = 2131296262;
			
			// aapt resource value: 0x7f090009
			public const int linearLayout3 = 2131296265;
			
			// aapt resource value: 0x7f09000c
			public const int linearLayout4 = 2131296268;
			
			// aapt resource value: 0x7f090021
			public const int lockImageView = 2131296289;
			
			// aapt resource value: 0x7f09002a
			public const int loginBtn = 2131296298;
			
			// aapt resource value: 0x7f090028
			public const int loginStatusProgress = 2131296296;
			
			// aapt resource value: 0x7f090029
			public const int loginStatusText = 2131296297;
			
			// aapt resource value: 0x7f09002f
			public const int map = 2131296303;
			
			// aapt resource value: 0x7f09003b
			public const int menu_mylocation = 2131296315;
			
			// aapt resource value: 0x7f09003d
			public const int menu_refresh = 2131296317;
			
			// aapt resource value: 0x7f09003c
			public const int menu_search = 2131296316;
			
			// aapt resource value: 0x7f090000
			public const int none = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int normal = 2131296257;
			
			// aapt resource value: 0x7f090027
			public const int password = 2131296295;
			
			// aapt resource value: 0x7f090037
			public const int rentalFromStation = 2131296311;
			
			// aapt resource value: 0x7f09003a
			public const int rentalPrice = 2131296314;
			
			// aapt resource value: 0x7f090034
			public const int rentalTime = 2131296308;
			
			// aapt resource value: 0x7f090035
			public const int rentalTimePrimary = 2131296309;
			
			// aapt resource value: 0x7f090036
			public const int rentalTimeSecondary = 2131296310;
			
			// aapt resource value: 0x7f090038
			public const int rentalToStation = 2131296312;
			
			// aapt resource value: 0x7f090002
			public const int satellite = 2131296258;
			
			// aapt resource value: 0x7f090023
			public const int streetViewImg = 2131296291;
			
			// aapt resource value: 0x7f090022
			public const int streetViewSpinner = 2131296290;
			
			// aapt resource value: 0x7f090003
			public const int terrain = 2131296259;
			
			// aapt resource value: 0x7f090012
			public const int text = 2131296274;
			
			// aapt resource value: 0x7f090025
			public const int textView1 = 2131296293;
			
			// aapt resource value: 0x7f090017
			public const int textView2 = 2131296279;
			
			// aapt resource value: 0x7f09000b
			public const int textView4 = 2131296267;
			
			// aapt resource value: 0x7f090039
			public const int textView5 = 2131296313;
			
			// aapt resource value: 0x7f09000f
			public const int titleText = 2131296271;
			
			// aapt resource value: 0x7f090026
			public const int username = 2131296294;
			
			// aapt resource value: 0x7f090010
			public const int view1 = 2131296272;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int DrawerAroundItem = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int DrawerHeader = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int DrawerItemLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int FavoriteItem = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int InfoPaneLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int LoginDialogLayout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Main = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int MapLayout = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int RentalItem = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0b0000
			public const int map_menu = 2131427328;
			
			// aapt resource value: 0x7f0b0001
			public const int rentals_menu = 2131427329;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f060000
			public const int bike = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int bike_separator = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int ic_lock = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int map = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int map_placeholder = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int pin = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int star_depressed = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int star_off = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int star_on = 2131099656;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070017
			public const int app_name = 2131165207;
			
			// aapt resource value: 0x7f070011
			public const int auth_client_needs_enabling_title = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int auth_client_needs_installation_title = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int auth_client_needs_update_title = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int auth_client_play_services_err_notification_msg = 2131165204;
			
			// aapt resource value: 0x7f070015
			public const int auth_client_requested_by_msg = 2131165205;
			
			// aapt resource value: 0x7f070010
			public const int auth_client_using_bad_version_title = 2131165200;
			
			// aapt resource value: 0x7f07001a
			public const int close_drawer = 2131165210;
			
			// aapt resource value: 0x7f070007
			public const int common_google_play_services_enable_button = 2131165191;
			
			// aapt resource value: 0x7f070006
			public const int common_google_play_services_enable_text = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int common_google_play_services_enable_title = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int common_google_play_services_install_button = 2131165188;
			
			// aapt resource value: 0x7f070002
			public const int common_google_play_services_install_text_phone = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int common_google_play_services_install_text_tablet = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int common_google_play_services_install_title = 2131165185;
			
			// aapt resource value: 0x7f07000a
			public const int common_google_play_services_unknown_issue = 2131165194;
			
			// aapt resource value: 0x7f07000c
			public const int common_google_play_services_unsupported_text = 2131165196;
			
			// aapt resource value: 0x7f07000b
			public const int common_google_play_services_unsupported_title = 2131165195;
			
			// aapt resource value: 0x7f07000d
			public const int common_google_play_services_update_button = 2131165197;
			
			// aapt resource value: 0x7f070009
			public const int common_google_play_services_update_text = 2131165193;
			
			// aapt resource value: 0x7f070008
			public const int common_google_play_services_update_title = 2131165192;
			
			// aapt resource value: 0x7f07000e
			public const int common_signin_button_text = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int common_signin_button_text_long = 2131165199;
			
			// aapt resource value: 0x7f070016
			public const int hello = 2131165206;
			
			// aapt resource value: 0x7f070000
			public const int library_name = 2131165184;
			
			// aapt resource value: 0x7f070019
			public const int open_drawer = 2131165209;
			
			// aapt resource value: 0x7f070018
			public const int search_hint = 2131165208;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f0a0000
			public const int drawer_item_shadow = 2131361792;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f050000
			public const int searchable = 2131034112;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MapAttrs = new int[]
			{
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981};
			
			// aapt resource value: 1
			public const int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 2
			public const int MapAttrs_cameraTargetLat = 2;
			
			// aapt resource value: 3
			public const int MapAttrs_cameraTargetLng = 3;
			
			// aapt resource value: 4
			public const int MapAttrs_cameraTilt = 4;
			
			// aapt resource value: 5
			public const int MapAttrs_cameraZoom = 5;
			
			// aapt resource value: 0
			public const int MapAttrs_mapType = 0;
			
			// aapt resource value: 6
			public const int MapAttrs_uiCompass = 6;
			
			// aapt resource value: 7
			public const int MapAttrs_uiRotateGestures = 7;
			
			// aapt resource value: 8
			public const int MapAttrs_uiScrollGestures = 8;
			
			// aapt resource value: 9
			public const int MapAttrs_uiTiltGestures = 9;
			
			// aapt resource value: 10
			public const int MapAttrs_uiZoomControls = 10;
			
			// aapt resource value: 11
			public const int MapAttrs_uiZoomGestures = 11;
			
			// aapt resource value: 12
			public const int MapAttrs_useViewLifecycle = 12;
			
			// aapt resource value: 13
			public const int MapAttrs_zOrderOnTop = 13;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
